use crate::{
    felt::Felt,
    funvec::{FunVec, FUNVEC_AUTHENTICATIONS},
};

#[derive(Debug, Default, Clone, Copy, PartialEq)]
pub struct Witness {
    // The authentication values: all the siblings of the subtree generated by the queried indices,
    // bottom layer up, left to right.
    pub authentications: FunVec<Felt, FUNVEC_AUTHENTICATIONS>,
}
